/**
 * Known emulator backends that RetroOasis can integrate with.
 * Each backend handles one or more Nintendo systems.
 *
 * The app does NOT bundle these backends — users must have them installed
 * or the app provides guided setup.
 */
export interface BackendDefinition {
  id: string;
  name: string;
  systems: string[];
  description: string;
  executableName: string;
  supportsNetplay: boolean;
  supportsSaveStates: boolean;
  website: string;
  notes: string[];
}

export const KNOWN_BACKENDS: BackendDefinition[] = [
  {
    id: 'fceux',
    name: 'FCEUX',
    systems: ['nes'],
    description: 'Highly compatible NES/Famicom emulator',
    executableName: 'fceux',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://fceux.com',
    notes: ['Good netplay support', 'Lua scripting available'],
  },
  {
    id: 'snes9x',
    name: 'Snes9x',
    systems: ['snes'],
    description: 'Popular and accurate SNES emulator',
    executableName: 'snes9x',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.snes9x.com',
    notes: ['Strong compatibility', 'Netplay via built-in support'],
  },
  {
    id: 'bsnes',
    name: 'bsnes',
    systems: ['snes'],
    description: 'Cycle-accurate SNES emulator',
    executableName: 'bsnes',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/bsnes-emu/bsnes',
    notes: ['Highest accuracy', 'Higher system requirements'],
  },
  {
    id: 'mgba',
    name: 'mGBA',
    systems: ['gb', 'gbc', 'gba'],
    description: 'Fast and accurate Game Boy Advance emulator (also supports GB/GBC)',
    executableName: 'mgba',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://mgba.io',
    notes: ['Link cable emulation', 'Excellent compatibility', 'Active development'],
  },
  {
    id: 'gambatte',
    name: 'Gambatte',
    systems: ['gb', 'gbc'],
    description: 'Accurate Game Boy / Game Boy Color emulator',
    executableName: 'gambatte',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/sinamas/gambatte',
    notes: ['Very high accuracy for GB/GBC'],
  },
  {
    id: 'sameboy',
    name: 'SameBoy',
    systems: ['gb', 'gbc'],
    description: 'Highly accurate Game Boy and Game Boy Color emulator with link cable support',
    executableName: 'sameboy',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://sameboy.github.io',
    notes: [
      'Best-in-class GB/GBC accuracy',
      'Link cable emulation via TCP (--link-address)',
      'Excellent for Pokémon Gen I/II trades and battles',
      'Open source (MIT license)',
    ],
  },
  {
    id: 'vbam',
    name: 'VisualBoyAdvance-M',
    systems: ['gb', 'gbc', 'gba'],
    description: 'Feature-rich Game Boy Advance (and GB/GBC) emulator with link cable netplay',
    executableName: 'visualboyadvance-m',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://visualboyadvance-m.org',
    notes: [
      'Link cable emulation over network (--link-host)',
      'Supports GBA, GBC, and GB ROMs',
      'Good compatibility for Pokémon Gen III link features',
      'Open source (GPLv2)',
    ],
  },
  {
    id: 'mupen64plus',
    name: 'Mupen64Plus',
    systems: ['n64'],
    description: 'Cross-platform N64 emulator with plugin architecture',
    executableName: 'mupen64plus',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://mupen64plus.org',
    notes: [
      'Install (Linux): sudo apt install mupen64plus mupen64plus-audio-sdl mupen64plus-input-sdl mupen64plus-video-glide64mk2',
      'Install (macOS): brew install mupen64plus',
      'Install (Windows): download from https://mupen64plus.org/releases/',
      'Detection: app checks for "mupen64plus" in PATH; ensure it is on your PATH after install',
      'Netplay args: --netplay-host <host> --netplay-port <port> --netplay-player <slot>',
      'Analog stick: requires mupen64plus-input-sdl plugin with "AnalogDeadzone" and "AnalogPeak" calibration',
      'Recommended video plugin: mupen64plus-video-glide64mk2 (default) or mupen64plus-video-rice',
      'For best party-game performance use GlideN64 (mupen64plus-video-gliden64) when available',
    ],
  },
  {
    id: 'project64',
    name: 'Project64',
    systems: ['n64'],
    description: 'Popular Windows N64 emulator',
    executableName: 'project64',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://www.pj64-emu.com',
    notes: ['Windows only', 'Good compatibility'],
  },
  {
    id: 'melonds',
    name: 'melonDS',
    systems: ['nds'],
    description: 'Fast and accurate Nintendo DS emulator with local wireless support',
    executableName: 'melonDS',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://melonds.kuribo64.net',
    notes: [
      'Core of this repository — the melonDS C++ source is embedded in /src',
      'Install (Linux): sudo apt install melonds  OR build from /src with cmake',
      'Install (macOS): brew install melonds',
      'Install (Windows): download from https://melonds.kuribo64.net',
      'Detection: app checks for "melonDS" in PATH; ensure it is on your PATH after install',
      'Local wireless: run multiple melonDS instances; they discover each other automatically',
      'Wi-Fi relay args: --wifi-host <host> --wifi-port <port>',
      'Screen layout: --screen-layout=stacked|side-by-side|top-focus|bottom-focus',
      'Touchscreen: --touch-mouse enables mouse-driven bottom screen input',
      'WFC DNS override: --wfc-dns=<ip> for Wiimmfi (178.62.43.212) or other WFC replacements',
      'BIOS/firmware: place NDS BIOS (bios7.bin, bios9.bin) and firmware.bin in ~/.config/melonDS/',
      'DSi mode: place DSi BIOS files (bios7i.bin, bios9i.bin, nand.bin) alongside the above',
      'DSi mode CLI arg: --dsi-mode (auto-detects DSiWare ROMs and enables DSi hardware features)',
      'Save states: Ctrl+1-8 to save slot, Shift+1-8 to load slot',
      'Screen swap hotkey: F11 swaps top/bottom screens while running',
    ],
  },
  {
    id: 'desmume',
    name: 'DeSmuME',
    systems: ['nds'],
    description: 'Mature Nintendo DS emulator with wide game compatibility',
    executableName: 'desmume',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://desmume.org',
    notes: [
      'Wide game compatibility — good fallback when melonDS has issues',
      'Install (Linux): sudo apt install desmume',
      'Install (macOS): brew install --cask desmume  OR build from source',
      'Install (Windows): download from https://desmume.org/download/',
      'Detection: app checks for "desmume" in PATH',
      'No built-in Wi-Fi/WFC netplay support — relay-only sessions via RetroOasis TCP relay',
      'Use melonDS for WFC / Pokémon online features; DeSmuME is for local or single-player',
      'Performance: --num-cores=2 for dual-core CPU utilization on older hardware',
      'BIOS: DeSmuME can run without BIOS files (HLE mode), though BIOS improves compatibility',
    ],
  },
  {
    id: 'nestopia',
    name: 'Nestopia UE',
    systems: ['nes'],
    description: 'Highly accurate NES/Famicom emulator focused on hardware precision',
    executableName: 'nestopia',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/0ldsk00l/nestopia',
    notes: [
      'Best-in-class NES accuracy (cycle-exact CPU and PPU emulation)',
      'Install (Linux): sudo apt install nestopia  OR build from source',
      'Install (macOS): brew install nestopia-ue',
      'Install (Windows): download from https://github.com/0ldsk00l/nestopia/releases',
      'Detection: app checks for "nestopia" in PATH',
      'No built-in netplay; sessions use RetroOasis TCP relay',
      'Supports FDS (Famicom Disk System) with BIOS image',
      'Open source (GPLv2) — active fork of original Nestopia',
      'Debug: launch with --log-level=debug for verbose output',
    ],
  },
  {
    id: 'higan',
    name: 'higan / ares',
    systems: ['nes', 'snes', 'gb', 'gbc', 'gba'],
    description: 'Cycle-accurate multi-system emulator (higan / ares successor)',
    executableName: 'ares',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://ares-emu.net',
    notes: [
      'Highest accuracy available for NES, SNES, GB, GBC, and GBA',
      'Install (Linux): build from source at https://github.com/ares-emulator/ares',
      'Install (macOS): brew install ares',
      'Install (Windows): download from https://ares-emu.net/download',
      'Detection: app checks for "ares" in PATH',
      'No built-in netplay; relay-only sessions via RetroOasis TCP relay',
      'Launch syntax: ares --system <System> <rom>  (e.g. ares --system SNES game.sfc)',
      'Higher system requirements than Snes9x/mGBA due to cycle-accuracy',
      'Open source (ISC license)',
      'Debug: --no-fast-boot disables BIOS skip; --verbose for detailed logs',
    ],
  },
  {
    id: 'retroarch',
    name: 'RetroArch',
    systems: ['nes', 'snes', 'gb', 'gbc', 'gba', 'n64', 'nds', 'gc', 'wii', 'wiiu', '3ds', 'genesis', 'dreamcast', 'psx', 'ps2', 'psp'],
    description: 'Universal open-source emulator frontend using libretro cores',
    executableName: 'retroarch',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.retroarch.com',
    notes: [
      'Install (Linux): sudo apt install retroarch  OR flatpak install flathub org.libretro.RetroArch',
      'Install (macOS): brew install retroarch',
      'Install (Windows): download from https://www.retroarch.com/?page=platforms',
      'Detection: app checks for "retroarch" in PATH',
      'Requires a libretro core — specify via coreLibraryPath option',
      'Recommended cores: fceumm or nestopia (NES), snes9x (SNES), mgba (GB/GBC/GBA), genesis_plus_gx (SEGA Genesis/Mega Drive)',
      'Install cores: retroarch --menu → Load Core → Download',
      'Netplay host: --host --port <port>',
      'Netplay client: --connect <host> --port <port>',
      'Debug / verbose: --verbose flag enables detailed log output',
      'Save states: F2 save, F4 load (default hotkeys)',
      'Open source (GPLv3)',
    ],
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    systems: ['gc', 'wii'],
    description: 'The premier GameCube and Wii emulator with netplay support',
    executableName: 'dolphin-emu',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://dolphin-emu.org',
    notes: [
      'Install (Linux): sudo apt install dolphin-emu  OR flatpak install flathub org.DolphinEmu.dolphin-emu',
      'Install (macOS): brew install --cask dolphin',
      'Install (Windows): download from https://dolphin-emu.org/download/',
      'Detection: app checks for "dolphin-emu" in PATH',
      'Launch a game: dolphin-emu -b -e <rom>  (-b = batch mode, exits when done)',
      'Netplay host: dolphin-emu -b -e <rom> --no-gui (use relay for session bridging)',
      'Supported ROM formats: .gcm (raw GC disc), .iso, .gcz (compressed), .rvz (newer compressed)',
      'Memory cards: placed in <UserDir>/GC/ (Slot A = MemoryCardA.USA.raw)',
      'Debug: dolphin-emu --debugger opens the integrated debugger',
      'Recommended video backend: Vulkan or OpenGL (set in Graphics settings)',
      'For best online performance use the Netplay mode in the Dolphin GUI or via relay sessions',
      'Open source (GPLv2+)',
    ],
  },
  {
    id: 'citra',
    name: 'Citra / Lime3DS',
    systems: ['3ds'],
    description: 'Nintendo 3DS emulator with local wireless and internet multiplayer',
    executableName: 'citra',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://lime3ds.github.io',
    notes: [
      'Citra was discontinued in 2024; Lime3DS (https://lime3ds.github.io) is the active fork',
      'Install (Linux): flatpak install flathub io.github.lime3ds.Lime3DS  OR build from source',
      'Install (macOS): brew install --cask lime3ds',
      'Install (Windows): download from https://github.com/Lime3DS/Lime3DS/releases',
      'Detection: app checks for "citra" or "lime3ds" in PATH',
      'Launch: citra <rom>  (supports .3ds, .cia, .3dsx, .cci formats)',
      'Multiplayer room host: citra-room --port <port> --name <room_name> --max-members <n>',
      'Multiplayer client: connect via Citra GUI → Multiplayer → Direct Connect to IP',
      'For relay sessions: relay bridges TCP at infrastructure level, launch game normally',
      'AES keys: requires title.db and seeddb.bin for encrypted titles (.cia)',
      'System archives: required for some titles (Home Menu, etc.) — dump from real hardware',
      'Save states: Ctrl+N save, Ctrl+A load (slot-based)',
      'Open source (GPLv2)',
    ],
  },
  {
    id: 'flycast',
    name: 'Flycast',
    systems: ['dreamcast'],
    description: 'Accurate Dreamcast and arcade emulator with online netplay',
    executableName: 'flycast',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://flycast.org',
    notes: [
      'Available as a standalone emulator or as the flycast_libretro RetroArch core',
      'Relay netplay: relay bridges TCP at infrastructure level; use RetroArch --host/--connect for relay sessions',
      'Standalone netplay: experimental built-in online; relay is recommended for stable sessions',
      'Install (Linux): build from source at https://github.com/flyinghead/flycast',
      'Install (macOS): brew install flycast  OR build from source',
      'Install (Windows): download from https://github.com/flyinghead/flycast/releases',
      'Open source (GPLv2)',
    ],
  },
  {
    id: 'duckstation',
    name: 'DuckStation',
    systems: ['psx'],
    description: 'Highly accurate PlayStation emulator with fast rendering',
    executableName: 'duckstation-qt',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://www.duckstation.org',
    notes: [
      'No built-in netplay CLI flags; relay-only netplay via RetroOasis TCP relay',
      'Install (Linux): flatpak install flathub org.duckstation.DuckStation  OR build from source',
      'Install (macOS): download from https://www.duckstation.org',
      'Install (Windows): download from https://www.duckstation.org',
      'Supports .bin/.cue, .iso, .img, .chd, .pbp ROM formats',
      'BIOS: requires PS1 BIOS image (scph1001.bin or similar)',
      'Open source (GPLv3)',
    ],
  },
  {
    id: 'pcsx2',
    name: 'PCSX2',
    systems: ['ps2'],
    description: 'Mature and accurate PlayStation 2 emulator',
    executableName: 'pcsx2',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://pcsx2.net',
    notes: [
      'Relay netplay: relay bridges TCP at infrastructure level; no native CLI netplay flags needed',
      'Launch with -- <rom> to pass ROM path after PCSX2 options',
      'Install (Linux): flatpak install flathub net.pcsx2.PCSX2  OR build from source',
      'Install (macOS): download from https://pcsx2.net/downloads/',
      'Install (Windows): download from https://pcsx2.net/downloads/',
      'BIOS: requires PS2 BIOS files (place in BIOS directory)',
      'Supports .iso, .bin/.cue, .chd ROM formats',
      'Open source (GPLv3)',
    ],
  },
  {
    id: 'ppsspp',
    name: 'PPSSPP',
    systems: ['psp'],
    description: 'The best PSP emulator with ad-hoc multiplayer support',
    executableName: 'ppsspp',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.ppsspp.org',
    notes: [
      'Ad-hoc relay: --adhoc-server <host>:<port> connects to relay for bridged ad-hoc sessions',
      'Install (Linux): build from source at https://github.com/hrydgard/ppsspp',
      'Install (macOS): download from https://www.ppsspp.org/downloads.html',
      'Install (Windows): download from https://www.ppsspp.org/downloads.html',
      'Supports .iso, .cso, .pbp, .elf ROM formats',
      'Open source (GPLv2)',
    ],
  },
  {
    id: 'cemu',
    name: 'Cemu',
    systems: ['wiiu'],
    description: 'Highly accurate Nintendo Wii U emulator',
    executableName: 'Cemu',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://cemu.info',
    notes: [
      'Relay netplay: relay bridges TCP at infrastructure level; Cemu has no built-in netplay CLI flags',
      'Install (Linux): flatpak install flathub info.cemu.Cemu  OR download from https://cemu.info',
      'Install (macOS): download from https://cemu.info/download.html',
      'Install (Windows): download from https://cemu.info/download.html',
      'Requires Wii U keys file (keys.txt) and game files in .wud/.wux/.iso/.rpx/.wua format',
      'Open source (MPL-2.0) since 2022',
    ],
  },
];
