/**
 * Known emulator backends that RetroOasis can integrate with.
 * Each backend handles one or more Nintendo systems.
 *
 * The app does NOT bundle these backends — users must have them installed
 * or the app provides guided setup.
 */

/**
 * Capability matrix for a single emulator backend.
 * Each field reflects a concrete feature that the orchestration layer
 * can rely on when building launch arguments or managing sessions.
 */
export interface BackendCapabilities {
  /** Backend can launch ROMs as a local child process via the bridge. */
  localLaunch: boolean;
  /**
   * Backend supports networked multiplayer — either through built-in CLI
   * flags (e.g. FCEUX --net, Snes9x -netplay, Mupen64Plus --netplay-host)
   * or through the RetroOasis TCP relay (relay-only backends still count
   * because the bridge can bridge their TCP connections).
   */
  netplay: boolean;
  /** Backend accepts a save-file directory and writes SRAM / save states there. */
  savePath: boolean;
  /** Backend can load an external controller remapping / profile config file. */
  controllerProfile: boolean;
  /**
   * Backend supports link cable emulation over TCP.
   * True only for emulators that expose a `--link-host` / `--link-address`
   * style flag (mGBA, SameBoy, VisualBoyAdvance-M).
   */
  linkCable: boolean;
}

export interface BackendDefinition {
  id: string;
  name: string;
  systems: string[];
  description: string;
  executableName: string;
  supportsNetplay: boolean;
  supportsSaveStates: boolean;
  website: string;
  notes: string[];
  /** Fine-grained capability matrix for orchestration decisions. */
  capabilities: BackendCapabilities;
}

export const KNOWN_BACKENDS: BackendDefinition[] = [
  {
    id: 'fceux',
    name: 'FCEUX',
    systems: ['nes'],
    description: 'Highly compatible NES/Famicom emulator',
    executableName: 'fceux',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://fceux.com',
    notes: ['Good netplay support', 'Lua scripting available'],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'snes9x',
    name: 'Snes9x',
    systems: ['snes'],
    description: 'Popular and accurate SNES emulator',
    executableName: 'snes9x',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.snes9x.com',
    notes: ['Strong compatibility', 'Netplay via built-in support'],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'bsnes',
    name: 'bsnes',
    systems: ['snes'],
    description: 'Cycle-accurate SNES emulator',
    executableName: 'bsnes',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/bsnes-emu/bsnes',
    notes: ['Highest accuracy', 'Higher system requirements'],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'mgba',
    name: 'mGBA',
    systems: ['gb', 'gbc', 'gba'],
    description: 'Fast and accurate Game Boy Advance emulator (also supports GB/GBC)',
    executableName: 'mgba',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://mgba.io',
    notes: ['Link cable emulation', 'Excellent compatibility', 'Active development'],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: true },
  },
  {
    id: 'gambatte',
    name: 'Gambatte',
    systems: ['gb', 'gbc'],
    description: 'Accurate Game Boy / Game Boy Color emulator',
    executableName: 'gambatte',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/sinamas/gambatte',
    notes: ['Very high accuracy for GB/GBC'],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: false, linkCable: false },
  },
  {
    id: 'sameboy',
    name: 'SameBoy',
    systems: ['gb', 'gbc'],
    description: 'Highly accurate Game Boy and Game Boy Color emulator with link cable support',
    executableName: 'sameboy',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://sameboy.github.io',
    notes: [
      'Best-in-class GB/GBC accuracy',
      'Link cable emulation via TCP (--link-address)',
      'Excellent for Pokémon Gen I/II trades and battles',
      'Open source (MIT license)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: true },
  },
  {
    id: 'vbam',
    name: 'VisualBoyAdvance-M',
    systems: ['gb', 'gbc', 'gba'],
    description: 'Feature-rich Game Boy Advance (and GB/GBC) emulator with link cable netplay',
    executableName: 'visualboyadvance-m',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://visualboyadvance-m.org',
    notes: [
      'Link cable emulation over network (--link-host)',
      'Supports GBA, GBC, and GB ROMs',
      'Good compatibility for Pokémon Gen III link features',
      'Open source (GPLv2)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: true },
  },
  {
    id: 'mupen64plus',
    name: 'Mupen64Plus',
    systems: ['n64'],
    description: 'Cross-platform N64 emulator with plugin architecture',
    executableName: 'mupen64plus',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://mupen64plus.org',
    notes: [
      'Install (Linux): sudo apt install mupen64plus mupen64plus-audio-sdl mupen64plus-input-sdl mupen64plus-video-glide64mk2',
      'Install (macOS): brew install mupen64plus',
      'Install (Windows): download from https://mupen64plus.org/releases/',
      'Detection: app checks for "mupen64plus" in PATH; ensure it is on your PATH after install',
      'Netplay args: --netplay-host <host> --netplay-port <port> --netplay-player <slot>',
      'Analog stick: requires mupen64plus-input-sdl plugin with "AnalogDeadzone" and "AnalogPeak" calibration',
      'Recommended video plugin: mupen64plus-video-glide64mk2 (default) or mupen64plus-video-rice',
      'For best party-game performance use GlideN64 (mupen64plus-video-gliden64) when available',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'project64',
    name: 'Project64',
    systems: ['n64'],
    description: 'Popular Windows N64 emulator',
    executableName: 'project64',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://www.pj64-emu.com',
    notes: ['Windows only', 'Good compatibility'],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'melonds',
    name: 'melonDS',
    systems: ['nds'],
    description: 'Fast and accurate Nintendo DS emulator with local wireless support',
    executableName: 'melonDS',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://melonds.kuribo64.net',
    notes: [
      'Core of this repository — the melonDS C++ source is embedded in /src',
      'Install (Linux): sudo apt install melonds  OR build from /src with cmake',
      'Install (macOS): brew install melonds',
      'Install (Windows): download from https://melonds.kuribo64.net',
      'Detection: app checks for "melonDS" in PATH; ensure it is on your PATH after install',
      'Local wireless: run multiple melonDS instances; they discover each other automatically',
      'Wi-Fi relay args: --wifi-host <host> --wifi-port <port>',
      'Screen layout: --screen-layout=stacked|side-by-side|top-focus|bottom-focus',
      'Touchscreen: --touch-mouse enables mouse-driven bottom screen input',
      'WFC DNS override: --wfc-dns=<ip> for Wiimmfi (178.62.43.212) or other WFC replacements',
      'BIOS/firmware: place NDS BIOS (bios7.bin, bios9.bin) and firmware.bin in ~/.config/melonDS/',
      'DSi mode: place DSi BIOS files (bios7i.bin, bios9i.bin, nand.bin) alongside the above',
      'DSi mode CLI arg: --dsi-mode (auto-detects DSiWare ROMs and enables DSi hardware features)',
      'Save states: Ctrl+1-8 to save slot, Shift+1-8 to load slot',
      'Screen swap hotkey: F11 swaps top/bottom screens while running',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'desmume',
    name: 'DeSmuME',
    systems: ['nds'],
    description: 'Mature Nintendo DS emulator with wide game compatibility',
    executableName: 'desmume',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://desmume.org',
    notes: [
      'Wide game compatibility — good fallback when melonDS has issues',
      'Install (Linux): sudo apt install desmume',
      'Install (macOS): brew install --cask desmume  OR build from source',
      'Install (Windows): download from https://desmume.org/download/',
      'Detection: app checks for "desmume" in PATH',
      'No built-in Wi-Fi/WFC netplay support — relay-only sessions via RetroOasis TCP relay',
      'Use melonDS for WFC / Pokémon online features; DeSmuME is for local or single-player',
      'Performance: --num-cores=2 for dual-core CPU utilization on older hardware',
      'BIOS: DeSmuME can run without BIOS files (HLE mode), though BIOS improves compatibility',
    ],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'nestopia',
    name: 'Nestopia UE',
    systems: ['nes'],
    description: 'Highly accurate NES/Famicom emulator focused on hardware precision',
    executableName: 'nestopia',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://github.com/0ldsk00l/nestopia',
    notes: [
      'Best-in-class NES accuracy (cycle-exact CPU and PPU emulation)',
      'Install (Linux): sudo apt install nestopia  OR build from source',
      'Install (macOS): brew install nestopia-ue',
      'Install (Windows): download from https://github.com/0ldsk00l/nestopia/releases',
      'Detection: app checks for "nestopia" in PATH',
      'No built-in netplay; sessions use RetroOasis TCP relay',
      'Supports FDS (Famicom Disk System) with BIOS image',
      'Open source (GPLv2) — active fork of original Nestopia',
      'Debug: launch with --log-level=debug for verbose output',
    ],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'higan',
    name: 'higan / ares',
    systems: ['nes', 'snes', 'gb', 'gbc', 'gba'],
    description: 'Cycle-accurate multi-system emulator (higan / ares successor)',
    executableName: 'ares',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://ares-emu.net',
    notes: [
      'Highest accuracy available for NES, SNES, GB, GBC, and GBA',
      'Install (Linux): build from source at https://github.com/ares-emulator/ares',
      'Install (macOS): brew install ares',
      'Install (Windows): download from https://ares-emu.net/download',
      'Detection: app checks for "ares" in PATH',
      'No built-in netplay; relay-only sessions via RetroOasis TCP relay',
      'Launch syntax: ares --system <System> <rom>  (e.g. ares --system SNES game.sfc)',
      'Higher system requirements than Snes9x/mGBA due to cycle-accuracy',
      'Open source (ISC license)',
      'Debug: --no-fast-boot disables BIOS skip; --verbose for detailed logs',
    ],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: false, linkCable: false },
  },
  {
    id: 'retroarch',
    name: 'RetroArch',
    systems: ['nes', 'snes', 'gb', 'gbc', 'gba', 'n64', 'nds', 'gc', 'wii', 'wiiu', '3ds', 'switch', 'genesis', 'segacd', 'sms', 'dreamcast', 'psx', 'ps2', 'psp'],
    description: 'Universal open-source emulator frontend using libretro cores',
    executableName: 'retroarch',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.retroarch.com',
    notes: [
      'Install (Linux): sudo apt install retroarch  OR flatpak install flathub org.libretro.RetroArch',
      'Install (macOS): brew install retroarch',
      'Install (Windows): download from https://www.retroarch.com/?page=platforms',
      'Detection: app checks for "retroarch" in PATH',
      'Requires a libretro core — specify via coreLibraryPath option',
      'Recommended cores: fceumm or nestopia (NES), snes9x (SNES), mgba (GB/GBC/GBA), genesis_plus_gx (SEGA Genesis/Mega Drive/Sega CD/Master System/Game Gear)',
      'Install cores: retroarch --menu → Load Core → Download',
      'Netplay host: --host --port <port>',
      'Netplay client: --connect <host> --port <port>',
      'Debug / verbose: --verbose flag enables detailed log output',
      'Save states: F2 save, F4 load (default hotkeys)',
      'Open source (GPLv3)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    systems: ['gc', 'wii'],
    description: 'The premier GameCube and Wii emulator with netplay support',
    executableName: 'dolphin-emu',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://dolphin-emu.org',
    notes: [
      'Install (Linux): sudo apt install dolphin-emu  OR flatpak install flathub org.DolphinEmu.dolphin-emu',
      'Install (macOS): brew install --cask dolphin',
      'Install (Windows): download from https://dolphin-emu.org/download/',
      'Detection: app checks for "dolphin-emu" in PATH',
      'Launch a game: dolphin-emu -b -e <rom>  (-b = batch mode, exits when done)',
      'Netplay host: dolphin-emu -b -e <rom> --no-gui (use relay for session bridging)',
      'Supported ROM formats: .gcm (raw GC disc), .iso, .gcz (compressed), .rvz (newer compressed)',
      'Memory cards: placed in <UserDir>/GC/ (Slot A = MemoryCardA.USA.raw)',
      'Debug: dolphin-emu --debugger opens the integrated debugger',
      'Recommended video backend: Vulkan or OpenGL (set in Graphics settings)',
      'For best online performance use the Netplay mode in the Dolphin GUI or via relay sessions',
      'Open source (GPLv2+)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'citra',
    name: 'Citra / Lime3DS',
    systems: ['3ds'],
    description: 'Nintendo 3DS emulator with local wireless and internet multiplayer',
    executableName: 'citra',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://lime3ds.github.io',
    notes: [
      'Citra was discontinued in March 2024; Lime3DS (https://lime3ds.github.io) is the recommended active fork',
      'Install (Linux): flatpak install flathub io.github.lime3ds.Lime3DS  OR build from source',
      'Install (macOS): brew install --cask lime3ds',
      'Install (Windows): download from https://github.com/Lime3DS/Lime3DS/releases',
      'Detection: app checks for "citra" or "lime3ds" in PATH; configure full path in Settings → Emulator Paths',
      'Launch: citra <rom>  (supports .3ds, .cia, .3dsx, .cci formats)',
      '.3ds is the most common trimmed ROM format; .cia is the installable content archive format',
      'Multiplayer room host: citra-room --port <port> --name <room_name> --max-members <n>',
      'Multiplayer client: connect via Citra/Lime3DS GUI → Multiplayer → Direct Connect to Host IP',
      'For relay sessions: relay bridges TCP at infrastructure level — launch game normally, relay handles routing',
      'AES keys: requires aes_keys.txt (or title.db + seeddb.bin) for encrypted .cia titles — dump from real hardware',
      'Shared fonts: place shared_font.bin in the Citra system/ directory for games that require the system font',
      'System archives: Home Menu and some apps need system archives — dump with GodMode9 on real hardware',
      'Save states: Ctrl+N to save, Ctrl+A to load (slot-based); saves stored per game per slot',
      'Layout modes: Default (top 240p + bottom 240p stacked), Side-by-Side, Single Screen, Large Screen',
      'Large Screen layout: top screen scaled up, bottom screen small — best for action games played with a controller',
      '3D effect: stereoscopic 3D is emulated via anaglyph, interlaced, or side-by-side modes in Display settings',
      'Region: most dumps auto-detect region; force override via Edit → Configuration → System → Region',
      'Performance: OpenGL or Vulkan backend; enable hardware shaders for best FPS on GPU-intensive titles',
      'Shader cache: Lime3DS persists compiled shaders; first run of a game will be slow — subsequent runs are fast',
      'Open source (GPLv2); all Citra code is preserved in Lime3DS which continues to receive fixes',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'flycast',
    name: 'Flycast',
    systems: ['dreamcast'],
    description: 'Accurate Dreamcast and NAOMI arcade emulator with rollback netcode and VMU support',
    executableName: 'flycast',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://github.com/flyinghead/flycast',
    notes: [
      'Available as a standalone emulator OR as the flycast_libretro core inside RetroArch',
      'RetroArch + flycast_libretro is the recommended path for relay netplay — use --host/--connect flags',
      'Standalone Flycast 2.x includes experimental rollback netcode for NAOMI and Dreamcast titles',
      'Install (Linux): build from source at https://github.com/flyinghead/flycast  OR flatpak install flathub org.flycast.Flycast',
      'Install (macOS): brew install flycast  OR build from source',
      'Install (Windows): download from https://github.com/flyinghead/flycast/releases',
      'Detection: app checks for "flycast" in PATH; configure the full path in Settings → Emulator Paths',
      'BIOS: place dc_boot.bin (required) and dc_flash.bin (optional) in ~/.local/share/flycast/data/ (Linux/macOS) or %APPDATA%\\flycast\\data\\ (Windows)',
      'RetroArch BIOS path: place dc_boot.bin and dc_flash.bin in the RetroArch system/ directory',
      'ROM formats: .gdi (GD-ROM image, preferred for accuracy), .cdi (DiscJuggler), .chd (compressed), .bin/.cue',
      'CHD is the best space-saving format — use chdman or Dolphin Tool to convert from .gdi',
      'VMU saves: Flycast writes virtual VMU data as .bin files in the save directory; each port/slot gets its own file',
      'Save states: stored as .state (standalone) or .state<N> slot files (RetroArch); use F2/F4 in RetroArch',
      'VGA output: highest quality for compatible games; enable in Flycast settings or pass --cable-type=vga',
      'Region override: Flycast auto-detects from the disc; force with --region=ntsc-u|ntsc-j|pal for region-locked titles',
      'Performance: JIT recompiler enabled by default for full speed; pass --no-dynarec for interpreter (debugging only)',
      'NAOMI arcade support: Flycast also emulates NAOMI and NAOMI 2 hardware; pass the BIOS and ROM pairs',
      'Open source (GPLv2)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'duckstation',
    name: 'DuckStation',
    systems: ['psx'],
    description: 'Highly accurate PlayStation emulator with fast rendering',
    executableName: 'duckstation-qt',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://www.duckstation.org',
    notes: [
      'No built-in netplay CLI flags; relay-only netplay via RetroOasis TCP relay',
      'Install (Linux): flatpak install flathub org.duckstation.DuckStation  OR build from source',
      'Install (macOS): download from https://www.duckstation.org',
      'Install (Windows): download from https://www.duckstation.org',
      'Supports .bin/.cue, .iso, .img, .chd, .pbp ROM formats',
      'BIOS: requires PS1 BIOS image (scph1001.bin or similar)',
      'Open source (GPLv3)',
    ],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'mednafen-psx',
    name: 'Mednafen PSX (Beetle PSX HW)',
    systems: ['psx'],
    description: 'Cycle-accurate PlayStation emulator via the Beetle PSX HW libretro core in RetroArch',
    executableName: 'retroarch',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://mednafen.github.io',
    notes: [
      'Runs as the Beetle PSX HW libretro core inside RetroArch — highest PSX accuracy available',
      'Supports hardware-renderer PGXP for reduced texture warping',
      'Install core in RetroArch: Main Menu → Load Core → Download → Beetle PSX HW',
      'Core file: mednafen_psx_hw_libretro (Linux: .so, Windows: .dll, macOS: .dylib)',
      'BIOS: place scph5501.bin (or equivalent) in your RetroArch system directory',
      'Netplay via RetroArch: --host --port <port> (host) / --connect <host> --port <port> (client)',
      'Install RetroArch (Linux): sudo apt install retroarch  OR flatpak install flathub org.libretro.RetroArch',
      'Open source (GPLv2)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'pcsx2',
    name: 'PCSX2',
    systems: ['ps2'],
    description: 'Mature and accurate PlayStation 2 emulator',
    executableName: 'pcsx2',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://pcsx2.net',
    notes: [
      'Relay netplay: relay bridges TCP at infrastructure level; no native CLI netplay flags needed',
      'Launch with -- <rom> to pass ROM path after PCSX2 options',
      'Install (Linux): flatpak install flathub net.pcsx2.PCSX2  OR build from source',
      'Install (macOS): download from https://pcsx2.net/downloads/',
      'Install (Windows): download from https://pcsx2.net/downloads/',
      'BIOS: requires PS2 BIOS files (place in BIOS directory)',
      'Supports .iso, .bin/.cue, .chd ROM formats',
      'Open source (GPLv3)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'ppsspp',
    name: 'PPSSPP',
    systems: ['psp'],
    description: 'The best PSP emulator with ad-hoc multiplayer support',
    executableName: 'ppsspp',
    supportsNetplay: true,
    supportsSaveStates: true,
    website: 'https://www.ppsspp.org',
    notes: [
      'Ad-hoc relay: --adhoc-server <host>:<port> connects to relay for bridged ad-hoc sessions',
      'Install (Linux): build from source at https://github.com/hrydgard/ppsspp',
      'Install (macOS): download from https://www.ppsspp.org/downloads.html',
      'Install (Windows): download from https://www.ppsspp.org/downloads.html',
      'Supports .iso, .cso, .pbp, .elf ROM formats',
      'Open source (GPLv2)',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'cemu',
    name: 'Cemu',
    systems: ['wiiu'],
    description: 'Highly accurate Nintendo Wii U emulator — open source since 2022, excellent game compatibility',
    executableName: 'Cemu',
    supportsNetplay: false,
    supportsSaveStates: true,
    website: 'https://cemu.info',
    notes: [
      'Relay netplay: relay bridges TCP at infrastructure level; Cemu has no built-in netplay CLI flags',
      'Install (Linux): flatpak install flathub info.cemu.Cemu  OR download from https://cemu.info',
      'Install (macOS): download from https://cemu.info/download.html',
      'Install (Windows): download from https://cemu.info/download.html',
      'Open source (MPL-2.0) since October 2022; Windows-only closed-source era is over',
      'Required keys: place keys.txt (Wii U title keys) in the Cemu mlc01/usr/title/ directory',
      'ROM formats: .wud (raw disc image), .wux (compressed disc), .iso, .rpx (executable), .wua (all-in-one archive)',
      '.wua is the most convenient single-file format; supported since Cemu 1.27',
      'Dumping games: use NUSPacker or Dumpling homebrew app on real Wii U hardware',
      'GamePad emulation: keyboard+mouse or right-click the game window for pointer control',
      'Pro Controller / Classic Controller: use SDL2-compatible gamepad; configure in Input Settings',
      'Graphics packs: community shader caches and resolution mods at https://github.com/ActualMandM/cemu_graphic_packs',
      'Performance: Vulkan (recommended) or OpenGL backend; enable async shader compilation to reduce stutter',
      'Online play (Pretendo): configure IPTABLES DNS to 94.23.2.42 for Pretendo network — replaces Nintendo Network',
      'Save location: Cemu mlc01/usr/save/<title-id>/',
      'Debug launch: Cemu -g <rom_path> --no-gui launches headless (useful for automation)',
      'Wii U GamePad second screen: requires a separate GamePad View window or UDP client (Cemu 1.x feature)',
      'Compatibility: 95 %+ of the Wii U library boots; major titles (MK8, Smash, Splatoon) run at full speed',
    ],
    capabilities: { localLaunch: true, netplay: false, savePath: true, controllerProfile: true, linkCable: false },
  },
  {
    id: 'ryujinx',
    name: 'Ryujinx',
    systems: ['switch'],
    description: 'Nintendo Switch emulator written in C# with accurate HLE and LDN local-wireless netplay',
    executableName: 'Ryujinx',
    supportsNetplay: true,
    supportsSaveStates: false,
    website: 'https://git.ryujinx.app/ryubing/ryujinx',
    notes: [
      'Ryujinx (community fork "RyuBing") is the active maintained branch after the original project closure in 2024',
      'Install (Linux): download AppImage from https://git.ryujinx.app/ryubing/ryujinx/releases',
      'Install (macOS): download .app bundle from releases; Apple Silicon (M1/M2) supported',
      'Install (Windows): download from https://git.ryujinx.app/ryubing/ryujinx/releases',
      'Required firmware: place Switch firmware (obtained from your own console) in ~/.config/Ryujinx/system/',
      'Required keys: prod.keys and title.keys from your Switch; place in ~/.config/Ryujinx/system/',
      'ROM formats: .nsp (eShop title), .xci (game cartridge image), .nca (content archive)',
      'XCI is preferred for physical game backups; NSP for eShop titles',
      'LDN netplay: Ryujinx supports LDN (local-device-network) protocol for wireless-style multiplayer',
      'LDN requires all players to use the same Ryujinx version and matching game + DLC versions',
      'LDN room: enable Multiplayer → Enable LAN/LDN Mode in Ryujinx settings; host creates a room via the app',
      'RetroOasis relay: for TCP relay sessions, launch game normally; relay bridges at network level',
      'Performance: Vulkan + NVDEC hardware decoding recommended; enable PPTC (persistent profile-guided tiered cache)',
      'Shader cache: pre-compiled caches available for popular titles — reduces compile stutter',
      'Mods/cheats: place in ~/.config/Ryujinx/mods/ directory (atmosphere format)',
      'Resolution scaling: 1×/2×/3× native; 2× (720p → 1440p) is the performance sweet spot',
      'Amiibo emulation: supported; use a virtual Amiibo tag from the Tools menu',
      'Compatibility: ~85 % of the Switch library runs; AAA titles (MK8DX, Smash Ultimate, Splatoon 3) boot at full speed',
    ],
    capabilities: { localLaunch: true, netplay: true, savePath: true, controllerProfile: true, linkCable: false },
  },
];
