set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)

# harfbuzzとQtの特定バージョンを除外
set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
set(VCPKG_POLICY_SKIP_DEPENDS_INCLUDE enabled)
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
