trigger:
- master

pool:
  name: Default
  demands:
   - agent.name -equals MacStadium-ARM64-Mac

workspace:
  clean: all
    
steps:
- script: mkdir $(Pipeline.Workspace)/build
  displayName: 'Create build environment'

- script: arch -arm64 cmake $(Build.SourcesDirectory) -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6);$(brew --prefix libarchive)" -DMACOS_BUNDLE_LIBS=ON -DMACOS_BUILD_DMG=ON -DUSE_QT6=ON
  displayName: 'Configure'
  workingDirectory: $(Pipeline.Workspace)/build
  
- script: arch -arm64 make -j$(sysctl -n hw.logicalcpu)
  displayName: 'Make'
  workingDirectory: $(Pipeline.Workspace)/build

- publish: $(Pipeline.Workspace)/build/melonDS.dmg
  artifact: melonDS.dmg

