export interface SeedGame {
  id: string;
  title: string;
  system: string;
  maxPlayers: number;
  multiplayerMode: string;
  tags: string[];
  badges: string[];
  description: string;
  supportsPublicLobby: boolean;
  supportsPrivateLobby: boolean;
  compatibilityNotes: string[];
  bestSessionMode: string;
  onlineRecommended: boolean;
  coverArt?: string;
}

/**
 * Seed data: 30 multiplayer-friendly Nintendo games across supported systems.
 * This drives the curated multiplayer library and lobby recommendations.
 */
export const MULTIPLAYER_GAMES_SEED: SeedGame[] = [
  // === NES ===
  {
    id: 'nes-contra',
    title: 'Contra',
    system: 'nes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Co-op'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'Classic run-and-gun co-op action. Grab a friend and save the world.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Excellent co-op experience'],
    bestSessionMode: 'Co-op',
    onlineRecommended: true,
  },
  {
    id: 'nes-double-dragon-ii',
    title: 'Double Dragon II: The Revenge',
    system: 'nes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Co-op'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'Beat-em-up classic with two-player co-op.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Smooth co-op mode'],
    bestSessionMode: 'Co-op',
    onlineRecommended: true,
  },
  {
    id: 'nes-rc-pro-am',
    title: 'R.C. Pro-Am',
    system: 'nes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Versus'],
    badges: ['Good Local'],
    description: 'Isometric RC car racing with competitive gameplay.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: [],
    bestSessionMode: 'Versus',
    onlineRecommended: false,
  },
  {
    id: 'nes-bubble-bobble',
    title: 'Bubble Bobble',
    system: 'nes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Co-op', 'Party'],
    badges: ['Good Local', 'Party Favorite'],
    description: 'Adorable bubble-blowing co-op platformer.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['True ending requires 2 players'],
    bestSessionMode: 'Co-op',
    onlineRecommended: true,
  },
  // === SNES ===
  {
    id: 'snes-super-bomberman',
    title: 'Super Bomberman',
    system: 'snes',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Party', 'Versus', 'Battle'],
    badges: ['Party Favorite', 'Great Online', 'Best with Friends'],
    description: 'The ultimate party battle game. Up to 4 players in explosive arena action.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Multitap required for 3-4 players'],
    bestSessionMode: 'Battle',
    onlineRecommended: true,
  },
  {
    id: 'snes-secret-of-mana',
    title: 'Secret of Mana',
    system: 'snes',
    maxPlayers: 3,
    multiplayerMode: 'local',
    tags: ['Co-op', '2P'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'Action RPG with up to 3-player co-op. A legendary multiplayer adventure.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Multitap needed for 3 players'],
    bestSessionMode: 'Co-op',
    onlineRecommended: true,
  },
  {
    id: 'snes-super-mario-kart',
    title: 'Super Mario Kart',
    system: 'snes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Versus'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'The original kart racer. Split-screen versus or battle mode.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Split screen may need layout adjustment'],
    bestSessionMode: 'Versus',
    onlineRecommended: true,
  },
  {
    id: 'snes-tetris-attack',
    title: 'Tetris Attack',
    system: 'snes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Versus'],
    badges: ['Great Online', 'Best with Friends'],
    description: 'Fast-paced competitive puzzle action. Perfect for quick matches.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: [],
    bestSessionMode: 'Quick Match',
    onlineRecommended: true,
  },
  {
    id: 'snes-street-fighter-ii-turbo',
    title: 'Street Fighter II Turbo',
    system: 'snes',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Versus', 'Battle'],
    badges: ['Great Online', 'Best with Friends'],
    description: 'Legendary fighting game. Challenge your friends to heated battles.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Low latency recommended for competitive play'],
    bestSessionMode: 'Versus',
    onlineRecommended: true,
  },
  // === Game Boy ===
  {
    id: 'gb-tetris',
    title: 'Tetris',
    system: 'gb',
    maxPlayers: 2,
    multiplayerMode: 'link',
    tags: ['2P', 'Versus', 'Link'],
    badges: ['Great Online', 'Link Mode'],
    description: 'The classic puzzle game with link cable versus mode.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required'],
    bestSessionMode: 'Quick Match',
    onlineRecommended: true,
  },
  {
    id: 'gb-pokemon-red',
    title: 'Pokémon Red',
    system: 'gb',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'The original Pokémon adventure. Trade and battle with friends via link cable.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required for trading and battles',
      'Cross-compatible with Pokémon Blue and Yellow',
    ],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'gb-pokemon-blue',
    title: 'Pokémon Blue',
    system: 'gb',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Collect and trade Pokémon with friends. Blue-exclusive Pokémon await.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required for trading and battles',
      'Cross-compatible with Pokémon Red and Yellow',
    ],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'gb-pokemon-yellow',
    title: 'Pokémon Yellow',
    system: 'gb',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Pikachu follows you everywhere. Trade and battle with Gen I classics.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required',
      'Cross-compatible with Pokémon Red and Blue',
    ],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  // === Game Boy Color ===
  {
    id: 'gbc-pokemon-gold',
    title: 'Pokémon Gold',
    system: 'gbc',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Trade and battle Pokémon with friends via link cable.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required for trading'],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'gbc-pokemon-silver',
    title: 'Pokémon Silver',
    system: 'gbc',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Trade and battle Pokémon with friends via link cable.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required for trading'],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'gbc-pokemon-crystal',
    title: 'Pokémon Crystal',
    system: 'gbc',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'The definitive Gen II experience. Trade and battle with friends.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required'],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'gbc-zelda-oracle-ages',
    title: 'The Legend of Zelda: Oracle of Ages',
    system: 'gbc',
    maxPlayers: 2,
    multiplayerMode: 'link',
    tags: ['2P', 'Link'],
    badges: ['Link Mode'],
    description: 'Link puzzle-adventure through time. Use a password or link cable to connect with Oracle of Seasons.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Password linking works without link cable',
      'Direct link cable connection enables special in-game trading',
    ],
    bestSessionMode: 'Link Trade',
    onlineRecommended: false,
  },
  {
    id: 'gbc-zelda-oracle-seasons',
    title: 'The Legend of Zelda: Oracle of Seasons',
    system: 'gbc',
    maxPlayers: 2,
    multiplayerMode: 'link',
    tags: ['2P', 'Link'],
    badges: ['Link Mode'],
    description: 'Action-adventure across changing seasons. Links to Oracle of Ages for the true ending.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Password linking works without link cable',
      'Direct link cable connection enables special in-game trading',
    ],
    bestSessionMode: 'Link Trade',
    onlineRecommended: false,
  },
  // === GBA ===
  {
    id: 'gba-pokemon-emerald',
    title: 'Pokémon Emerald',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Trade, battle, and explore the Battle Frontier with friends.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required', 'Wireless adapter features may be limited'],
    bestSessionMode: 'Trade/Battle Room',
    onlineRecommended: true,
  },
  {
    id: 'gba-pokemon-firered',
    title: 'Pokémon FireRed',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Relive Kanto and trade with friends.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link cable emulation required'],
    bestSessionMode: 'Trade/Battle Room',
    onlineRecommended: true,
  },
  {
    id: 'gba-mario-kart-super-circuit',
    title: 'Mario Kart: Super Circuit',
    system: 'gba',
    maxPlayers: 4,
    multiplayerMode: 'link',
    tags: ['4P', 'Versus', 'Link'],
    badges: ['Great Online', 'Link Mode', 'Best with Friends'],
    description: 'Portable kart racing with up to 4-player link cable support.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Requires link cable emulation for multiplayer'],
    bestSessionMode: 'Quick Race',
    onlineRecommended: true,
  },
  {
    id: 'gba-advance-wars',
    title: 'Advance Wars',
    system: 'gba',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Versus'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'Turn-based strategy with hot-seat and link multiplayer.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Hot-seat mode works without link cable'],
    bestSessionMode: 'Versus',
    onlineRecommended: false,
  },
  {
    id: 'gba-final-fantasy-tactics-advance',
    title: 'Final Fantasy Tactics Advance',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'link',
    tags: ['2P', 'Link'],
    badges: ['Link Mode'],
    description: 'Tactical RPG with link cable trading and battles.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Link features are optional'],
    bestSessionMode: 'Link Battle',
    onlineRecommended: false,
  },
  {
    id: 'gba-pokemon-ruby',
    title: 'Pokémon Ruby',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Explore Hoenn and complete your Pokédex with Gen III trades and battles.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required for trading and battles',
      'Cross-compatible with Pokémon Sapphire, FireRed, and LeafGreen',
    ],
    bestSessionMode: 'Trade/Battle Room',
    onlineRecommended: true,
  },
  {
    id: 'gba-pokemon-sapphire',
    title: 'Pokémon Sapphire',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Sapphire-exclusive Pokémon await — trade and battle across Hoenn.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required',
      'Cross-compatible with Pokémon Ruby, FireRed, and LeafGreen',
    ],
    bestSessionMode: 'Trade/Battle Room',
    onlineRecommended: true,
  },
  {
    id: 'gba-pokemon-leafgreen',
    title: 'Pokémon LeafGreen',
    system: 'gba',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Return to Kanto with updated graphics. Trade across generations with friends.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Link cable emulation required',
      'Cross-compatible with FireRed, Ruby, Sapphire, and Emerald',
    ],
    bestSessionMode: 'Trade/Battle Room',
    onlineRecommended: true,
  },
  {
    id: 'gba-zelda-four-swords',
    title: 'The Legend of Zelda: A Link to the Past & Four Swords',
    system: 'gba',
    maxPlayers: 4,
    multiplayerMode: 'link',
    tags: ['4P', 'Co-op', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Four-player cooperative Zelda action. Four Links must work together to rescue Zelda.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: [
      'Four Swords mode requires link cable emulation for 2–4 players',
      'Classic A Link to the Past campaign is single-player',
    ],
    bestSessionMode: 'Co-op',
    onlineRecommended: true,
  },
  // === N64 ===
  {
    id: 'n64-mario-kart-64',
    title: 'Mario Kart 64',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Versus', 'Party'],
    badges: ['Party Favorite', 'Great Online', 'Best with Friends'],
    description: 'Iconic 4-player kart racing. The definitive N64 party game.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['4-player split screen', 'Analog stick recommended'],
    bestSessionMode: 'Quick Race',
    onlineRecommended: true,
  },
  {
    id: 'n64-super-smash-bros',
    title: 'Super Smash Bros.',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Versus', 'Battle', 'Party'],
    badges: ['Party Favorite', 'Great Online', 'Best with Friends'],
    description: 'The original platform fighter. 4-player chaos at its finest.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Analog stick strongly recommended', 'Low latency important'],
    bestSessionMode: 'Battle',
    onlineRecommended: true,
  },
  {
    id: 'n64-mario-party-2',
    title: 'Mario Party 2',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Party', 'Co-op', 'Versus'],
    badges: ['Party Favorite', 'Best with Friends'],
    description: 'Board game fun with dozens of mini-games for 4 players.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Some mini-games use analog stick rotation'],
    bestSessionMode: 'Party Session',
    onlineRecommended: true,
  },
  {
    id: 'n64-mario-party-3',
    title: 'Mario Party 3',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Party', 'Co-op', 'Versus'],
    badges: ['Party Favorite', 'Best with Friends'],
    description: 'More boards, more mini-games, more party mayhem.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: [],
    bestSessionMode: 'Party Session',
    onlineRecommended: true,
  },
  {
    id: 'n64-goldeneye-007',
    title: 'GoldenEye 007',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Versus', 'Battle'],
    badges: ['Party Favorite', 'Good Local'],
    description: 'Legendary 4-player split-screen FPS action.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Split screen performance varies', 'Analog stick recommended'],
    bestSessionMode: 'Versus',
    onlineRecommended: false,
  },
  {
    id: 'n64-diddy-kong-racing',
    title: 'Diddy Kong Racing',
    system: 'n64',
    maxPlayers: 4,
    multiplayerMode: 'local',
    tags: ['4P', 'Versus'],
    badges: ['Good Local', 'Best with Friends'],
    description: 'Kart, hovercraft, and plane racing for up to 4 players.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: [],
    bestSessionMode: 'Quick Race',
    onlineRecommended: true,
  },
  // === NDS ===
  {
    id: 'nds-mario-kart-ds',
    title: 'Mario Kart DS',
    system: 'nds',
    maxPlayers: 8,
    multiplayerMode: 'online',
    tags: ['4P', 'Versus', 'Battle'],
    badges: ['Great Online', 'Party Favorite', 'Best with Friends'],
    description: 'The best portable Mario Kart. Race with up to 8 players online.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original Nintendo WFC servers are offline', 'Requires custom server or local wireless emulation'],
    bestSessionMode: 'Quick Race',
    onlineRecommended: true,
    coverArt: undefined,
  },
  {
    id: 'nds-new-super-mario-bros',
    title: 'New Super Mario Bros.',
    system: 'nds',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Versus', 'Battle'],
    badges: ['Good Local'],
    description: 'Classic Mario platforming with local wireless mini-games.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Wireless mini-games require local wireless emulation'],
    bestSessionMode: 'Battle',
    onlineRecommended: false,
  },
  {
    id: 'nds-pokemon-diamond',
    title: 'Pokémon Diamond',
    system: 'nds',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'Gen IV Pokémon trading and battling via local wireless.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original WFC servers offline', 'Local wireless trading via emulation'],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'nds-pokemon-heartgold',
    title: 'Pokémon HeartGold',
    system: 'nds',
    maxPlayers: 2,
    multiplayerMode: 'trade',
    tags: ['2P', 'Trade', 'Battle', 'Link'],
    badges: ['Link Mode', 'Best with Friends'],
    description: 'The beloved Johto remakes with trading and battling.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Local wireless emulation for trading'],
    bestSessionMode: 'Trade Room',
    onlineRecommended: true,
  },
  {
    id: 'nds-tetris-ds',
    title: 'Tetris DS',
    system: 'nds',
    maxPlayers: 4,
    multiplayerMode: 'online',
    tags: ['4P', 'Versus', 'Party'],
    badges: ['Great Online', 'Party Favorite'],
    description: 'Nintendo-themed Tetris with online and local wireless multiplayer.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original WFC servers offline', 'Touch controls optional'],
    bestSessionMode: 'Quick Match',
    onlineRecommended: true,
  },
  {
    id: 'nds-animal-crossing-wild-world',
    title: 'Animal Crossing: Wild World',
    system: 'nds',
    maxPlayers: 4,
    multiplayerMode: 'online',
    tags: ['4P', 'Co-op'],
    badges: ['Best with Friends'],
    description: 'Visit friends\' towns and play together in cozy island life.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original WFC servers offline', 'Requires custom server or local wireless'],
    bestSessionMode: 'Friend Visit',
    onlineRecommended: false,
  },
  // ---------------------------------------------------------------------------
  // Phase 14 — Zelda & Metroid Online
  // ---------------------------------------------------------------------------
  {
    id: 'nds-metroid-prime-hunters',
    title: 'Metroid Prime Hunters',
    system: 'nds',
    maxPlayers: 4,
    multiplayerMode: 'online',
    tags: ['4P', 'FPS', 'Competitive'],
    badges: ['Great Online', 'Wiimmfi Supported'],
    description: 'Intergalactic bounty hunters battle across alien arenas in this DS first-person shooter. Supports 4-player online deathmatch via Wiimmfi.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original WFC servers offline', 'Use Wiimmfi (178.62.43.212) via wfc-config', 'Stylus aiming recommended'],
    bestSessionMode: 'Deathmatch',
    onlineRecommended: true,
  },
  {
    id: 'nds-zelda-phantom-hourglass',
    title: 'The Legend of Zelda: Phantom Hourglass',
    system: 'nds',
    maxPlayers: 2,
    multiplayerMode: 'online',
    tags: ['2P', 'Versus', 'Adventure'],
    badges: ['Wiimmfi Supported'],
    description: 'Touch-screen adventure featuring a 2-player Battle Mode where one player controls Link and the other commands the Phantoms.',
    supportsPublicLobby: true,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Original WFC servers offline', 'Use Wiimmfi (178.62.43.212) via wfc-config', 'Full touch-screen controls'],
    bestSessionMode: 'Battle Mode',
    onlineRecommended: true,
  },
  {
    id: 'nds-zelda-spirit-tracks',
    title: 'The Legend of Zelda: Spirit Tracks',
    system: 'nds',
    maxPlayers: 2,
    multiplayerMode: 'local',
    tags: ['2P', 'Co-op', 'Adventure'],
    badges: ['Local Co-op'],
    description: 'Link and Princess Zelda work together — one controls Link, the other guides a phantom. Touch-screen adventure with local wireless co-op.',
    supportsPublicLobby: false,
    supportsPrivateLobby: true,
    compatibilityNotes: ['Local wireless only', 'Touch-screen controls', 'No WFC online mode'],
    bestSessionMode: 'Co-op',
    onlineRecommended: false,
  },
];
