/**
 * Phase 17 — In-app Notification Store
 *
 * Tracks per-player notifications generated by server-side events (achievement
 * unlocks, friend requests, DMs, etc.).  Purely in-memory; a SQLite-backed
 * variant can be added later following the pattern of SqliteGameRatingsStore.
 */

import { randomUUID } from 'crypto';

export type NotificationType =
  | 'achievement-unlocked'
  | 'friend-request'
  | 'friend-accepted'
  | 'dm-received'
  | 'tournament-result'
  | 'room-invite';

export interface AppNotification {
  id: string;
  playerId: string;
  type: NotificationType;
  title: string;
  body: string;
  read: boolean;
  createdAt: string;
  /** Optional: relevant entity ID (achievement id, room code, etc.) */
  entityId?: string;
}

/** Maximum notifications retained per player before oldest are evicted. */
const MAX_PER_PLAYER = 200;

export class NotificationStore {
  private readonly store = new Map<string, AppNotification[]>();

  private playerList(playerId: string): AppNotification[] {
    let list = this.store.get(playerId);
    if (!list) {
      list = [];
      this.store.set(playerId, list);
    }
    return list;
  }

  /** Add a notification for a player. */
  add(
    playerId: string,
    type: NotificationType,
    title: string,
    body: string,
    entityId?: string
  ): AppNotification {
    const notification: AppNotification = {
      id: randomUUID(),
      playerId,
      type,
      title,
      body,
      read: false,
      createdAt: new Date().toISOString(),
      entityId,
    };
    const list = this.playerList(playerId);
    list.unshift(notification); // newest first
    if (list.length > MAX_PER_PLAYER) {
      list.splice(MAX_PER_PLAYER);
    }
    return notification;
  }

  /** Get all notifications for a player (newest first). */
  list(playerId: string): AppNotification[] {
    return [...(this.store.get(playerId) ?? [])];
  }

  /** Mark a specific notification as read.  Returns true if found. */
  markRead(notificationId: string): boolean {
    for (const list of this.store.values()) {
      const n = list.find((x) => x.id === notificationId);
      if (n) {
        n.read = true;
        return true;
      }
    }
    return false;
  }

  /** Mark all notifications for a player as read.  Returns count marked. */
  markAllRead(playerId: string): number {
    const list = this.store.get(playerId);
    if (!list) return 0;
    let count = 0;
    for (const n of list) {
      if (!n.read) {
        n.read = true;
        count++;
      }
    }
    return count;
  }

  /** Count unread notifications for a player. */
  unreadCount(playerId: string): number {
    return (this.store.get(playerId) ?? []).filter((n) => !n.read).length;
  }
}
